NHCM.WebUI/Pages/Security/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NHCM.WebUI.Pages.Security
{
    
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

NHCM.WebUI/Pages/Security/AdminsRegistry.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NHCM.WebUI.Pages.Security
{

    [Authorize("SuperAdmin")]
    public class AdminsRegistryModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

NHCM.WebUI/Pages/Security/ChangePassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NHCM.WebUI.Pages.Security
{
    public class ChangePasswordModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

NHCM.WebUI/Pages/Security/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Test.Areas.Identity.Pages
{
    [AllowAnonymous]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

NHCM.WebUI/Pages/Security/InitialPasswordChange.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NHCM.Persistence;
using NHCM.Persistence.Infrastructure.Identity;

namespace NHCM.WebUI.Pages.Security
{

    [Authorize(Policy = "FreshUserPolicy")]
    public class InitialPasswordChangeModel : PageModel
    {
        #region VM
        [BindProperty]
        [Display(Name = "رمز عبور")]
        [Required(ErrorMessage = "رمز عبور فعلی ضروری میباشد")]
        [DataType(DataType.Password)]
        public string CurrentPassword { get; set; }

       
        [Display(Name = "رمز عبور جدید")]
        [Required(ErrorMessage = "رمز عبور ضروری میباشد")]
        [DataType(DataType.Password)]
        [BindProperty]
        public string NewPassword { get; set; }

        
        [Display(Name = "تکرار رمز عبور جدید")]
     //   [Compare("NewPassword", ErrorMessage = "رمز جدید و تاییدی آن مطابقت ندارد")]
        [Required(ErrorMessage ="لطفا رمز عبور خود را دوباره بنویسید")]
        [DataType(DataType.Password)]
        [BindProperty]
        public string NewPasswordConfirmation { get; set; }

        [BindProperty]
        public string Message { get; set; }
        #endregion VM
        #region DI
        private readonly UserManager<HCMUser> _userManager;
        private readonly SignInManager<HCMUser> _signInManager;
        private readonly HCMContext _context;
        public InitialPasswordChangeModel(UserManager<HCMUser> usermanager, SignInManager<HCMUser> signInManager, HCMContext context)
        {
            _userManager = usermanager;
            _signInManager = signInManager;
            _context = context;
        }
        #endregion DI


        public async Task<IActionResult> OnPostChangePassword()
        {
            HCMUser CurrentUser = await _userManager.FindByNameAsync(User.Identity.Name);
            IdentityResult PaswordChangeResult = await _userManager.ChangePasswordAsync(CurrentUser, CurrentPassword, NewPassword);

            if (PaswordChangeResult.Succeeded)
            {
                CurrentUser.PasswordChanged = true;
                await _userManager.UpdateAsync(CurrentUser);
                Message = "کاربر عزیز رمز عبور شما موفقانه تعغیر یافت";

                return Page();

            }
            else
            {
                foreach (var error in PaswordChangeResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                    Message += "\n " + error.Description;
                }
                return Page();
            }
            
            
   
        }
        public void OnGet()
        {

        }
    }
}

NHCM.WebUI/Pages/Security/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NHCM.Persistence.Identity.Infrastructure;
using NHCM.Persistence.Infrastructure.Identity;

namespace NHCM.WebUI.Pages.Security
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly SignInManager<HCMUser> _signInManger;
        private readonly UserManager<HCMUser> _userManager;
              
        public LoginModel(SignInManager<HCMUser> signInManager, UserManager<HCMUser> userManager)
        {
            _signInManger = signInManager;
            _userManager = userManager;
        }

        [BindProperty]
        [Required]
        public string UserName { get; set; }

        [BindProperty]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public async void OnGetAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");

            if (ModelState.IsValid)
            {
                var result = await _signInManger.PasswordSignInAsync(UserName, Password, false, false);

                if (result.Succeeded)
                {
                    if (!(await _userManager.FindByNameAsync(UserName)).PasswordChanged)
                        return LocalRedirect("~/Security/InitialPasswordChange");
                    else
                        return LocalRedirect("/index");
                }
                else
                {
                    if (result.IsLockedOut)
                    {
                        ModelState.AddModelError(string.Empty, "کاربر محترم حساب شما قفل شده است لطفا با بخش مدیر سیستم به تماس شوید");
                    }
                    ModelState.AddModelError(string.Empty, "نام کاربری یا رمز عبور اشتباه میباشد");
                    return Page();
                }
            }


            return Page();



        }
    }
}

NHCM.WebUI/Pages/Security/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using NHCM.Persistence.Infrastructure.Identity;


namespace NHCM.WebUI.Pages.Security
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<HCMUser> _signInManager;
       // private readonly ILogger<LogoutModel> _logger;

        public LogoutModel(SignInManager<HCMUser> signInManager, ILogger<LogoutModel> logger)
        {
            _signInManager = signInManager;
         //   _logger = logger;
        }

        public async Task<IActionResult> OnGet(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();
            ///  _logger.LogInformation("User logged out.");
            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return Page();
            }
        }

        //public async Task<IActionResult> OnPost(string returnUrl = null)
        //{
           
        //}
    }
}

NHCM.WebUI/Pages/Security/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NHCM.Application.Accounts.Commands;
using NHCM.Application.Lookup.Queries;
using NHCM.Application.Recruitment.Models;
using NHCM.Application.Recruitment.Queries;
using NHCM.Domain.Entities;
using NHCM.Persistence.Infrastructure.Identity;
using NHCM.Persistence.Infrastructure.Services;
using NHCM.WebUI.Types;
namespace NHCM.WebUI.Pages.Security
{
    [Authorize("UserRegistrar")]
    public class RegisterModel : BasePage
    {

        private readonly UserManager<HCMUser> _userManager;
        public int? SignedInUserOrganizationID { get; set; }

        public RegisterModel(UserManager<HCMUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task OnGetAsync()
        {

            SignedInUserOrganizationID = ((HCMUser)await _userManager.GetUserAsync(User)).OrganizationID;

            //Get Organization
            ListOfOrganization = new List<SelectListItem>();
            List<Organization> organizations = new List<Organization>();
            organizations = await Mediator.Send(new GetOrganiztionQuery() { Id = SignedInUserOrganizationID ?? default(int) });
            foreach (Organization organization in organizations)
                ListOfOrganization.Add(new SelectListItem(organization.Dari, organization.Id.ToString()));


            // Get List Of  Persons
            ListOfPerson = new List<SelectListItem>();
            List<SearchedPersonModel> searchedPeople = new List<SearchedPersonModel>();
            // CHANGE: change the SearchPersonQuery Request to include a property to bring all records not only 10000
            searchedPeople = await Mediator.Send(new SearchPersonQuery() { OrganizationId = SignedInUserOrganizationID, NoOfRecords = 10000 });

            foreach (SearchedPersonModel person in searchedPeople)
            {
                ListOfPerson.Add(new SelectListItem()
                {
                    Text = new StringBuilder() { }.Append(person.FirstName).Append(" فرزند ").Append(" ").Append(person.FatherName).ToString(),
                    Value = person.Id.ToString()
                });
            }
        }
        public async Task<IActionResult> OnPostSave([FromBody] CreateUserCommand command)
        {
            try
            {
                List<string> result = await Mediator.Send(command);
                return new JsonResult(new UIResult()
                {
                    Data = new { list = result },
                    Status = UIStatus.Success,
                    Text = "کاربر موفقانه ثبت سیستم شد" + "\n" + "رمز عبور: " +  result[0].ToString(),
                    Description = string.Empty

                });
            }
            catch (Exception ex)
            {
                return new JsonResult(CustomMessages.FabricateException(ex));
            }
        }

        public void OnPost()
        {
        }
    }
}

NHCM.WebUI/Pages/Security/Roles.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NHCM.Persistence.Infrastructure.Identity;

namespace NHCM.WebUI.Pages.Security
{
    public class RolesModel : PageModel
    {

        private readonly UserManager<HCMUser> _userManager;
        private readonly RoleManager<HCMRole> _roleManager;

        [MinLength(4, ErrorMessage = "نام رول حداقل باید دارای چهار حرف باشد")]
        [MaxLength(32, ErrorMessage = "نام رول حد اکثر میتواند دارای سی و دو حرف باشد")]
        [BindProperty]
        [Required]
        public string RoleName { get; set; }


        public string Message { get; set; }

        public RolesModel(UserManager<HCMUser> userManager, RoleManager<HCMRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public void OnGet()
        {

        }


        public async Task<IActionResult> OnPostCreateRole()
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await _roleManager.CreateAsync(new HCMRole() { Name = RoleName });

                if (result.Succeeded)
                {
                    Message = "نقش موفقانه ثبت سیستم شد";
                    return Page();
                }
                else
                {
                    foreach(var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);

                    }
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "درخواست شما درست نمیباشد");
                return Page();
            }
            return Page();

        }
    }
}

NHCM.WebUI/Pages/Security/UserInRole.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NHCM.Persistence.Infrastructure.Identity;

namespace NHCM.WebUI.Pages.Security
{
    public class UserInRoleModel : PageModel
    {

        public string Message { get; set; }
        public List<SelectListItem> ListOfUsers = new List<SelectListItem>();
        public List<SelectListItem> ListOfRoles = new List<SelectListItem>();


       
        [BindProperty]
        [Required]
        public string RoleId { get; set; }

        [BindProperty]
        [Required]
        public string UserId { get; set; }

        

        private readonly RoleManager<HCMRole> _roleManager;
        private readonly UserManager<HCMUser> _userManager;

        public UserInRoleModel(UserManager<HCMUser> userManager, RoleManager<HCMRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public  void OnGet()
        {
            List<HCMUser> users =  _userManager.Users.ToList();
            foreach (HCMUser user in users)
                ListOfUsers.Add(new SelectListItem() { Text = user.UserName, Value = user.Id.ToString() });


            List<HCMRole> roles = new List<HCMRole>();
            roles =  _roleManager.Roles.ToList();
            foreach (HCMRole role in roles)
                ListOfRoles.Add(new SelectListItem() { Text = role.Name, Value = role.Id.ToString() });
         



        }

        public async Task<IActionResult> OnPostAddUserInRole()
        {

            if (ModelState.IsValid)
            {

                HCMUser user = await _userManager.FindByIdAsync(UserId);
                HCMRole role = await _roleManager.FindByIdAsync(RoleId);

                IdentityResult result = await _userManager.AddToRoleAsync(user, role.Name);
                if (result.Succeeded)
                {
                    Message = $" موفقانه به  {user.UserName} تعین شد {role.Name}";
                    return Page();
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                    return Page();
                }
               
            }
            else
            {
                return Page();
            }
        }
    }
}

NHCM.WebUI/Pages/Security/AccessDenied.cshtml
@page
@model NHCM.WebUI.Pages.Security.AccessDeniedModel
@{
    ViewData["Title"] = "AccessDenied";
    Layout = null;
}




<h4>
    شما حق بازدید از این صفحه را ندارید
</h4>

NHCM.WebUI/Pages/Security/AdminsRegistry.cshtml
@page
@model NHCM.WebUI.Pages.Security.AdminsRegistryModel
@{
    ViewData["Title"] = "AdminsRegistry";
    Layout = "~/Pages/Security/Shared/_SecuritySharedLayout.cshtml";
}

<h2>AdminsRegistry</h2>

NHCM.WebUI/Pages/Security/ChangePassword.cshtml
@page
@model NHCM.WebUI.Pages.Security.ChangePasswordModel
@{
    ViewData["Title"] = "ChangePassword";
    Layout = "~/Pages/Security/Shared/_SecuritySharedLayout.cshtml";
}

<h2>ChangePassword</h2>

NHCM.WebUI/Pages/Security/InitialPasswordChange.cshtml
@page
@model NHCM.WebUI.Pages.Security.InitialPasswordChangeModel
@{
    ViewData["Title"] = "InitialPasswordChange";
    Layout = "~/Pages/Security/Shared/_SecuritySharedLayout.cshtml";
}
<div class="panel-heading">
    <h1 class="panel-title">تعغیر رمز عبور</h1>
</div>

<div class="panel-body">
    <div class="row">
        <div class="col-md-6 pull-right">
            <form method="post" class="form main-form page-component" type="form">
                <fieldset class="content-group">
                    <legend>تعغیر رمز عبور برای بار اول ضروری میباشد</legend>

                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 pull-right">
                            <div class="form-group has-feedback has-feedback-left">
                                <label asp-for="@Model.CurrentPassword" class="text-bold">


                                </label>

                                <span asp-validation-for="@Model.CurrentPassword" class="text-danger"></span>
                                <input asp-for="@Model.CurrentPassword" class="form-control" />
                                <div class="form-control-feedback">
                                    <i class="icon-user text-size-base">

                                    </i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 pull-right">
                            <div class="form-group has-feedback has-feedback-left">
                                <label asp-for="@Model.NewPassword" class="text-bold">


                                </label>

                                <span asp-validation-for="@Model.NewPassword" class="text-danger"></span>
                                <input asp-for="@Model.NewPassword" class="form-control" />
                                <div class="form-control-feedback">
                                    <i class="icon-user text-size-base">

                                    </i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 pull-right">
                            <div class="form-group has-feedback has-feedback-left">
                                <label asp-for="@Model.NewPasswordConfirmation" class="text-bold">


                                </label>

                                <span asp-validation-for="@Model.NewPasswordConfirmation" class="text-danger"></span>
                                <input asp-for="@Model.NewPasswordConfirmation" class="form-control" />
                                <div class="form-control-feedback">
                                    <i class="icon-user text-size-base">

                                    </i>
                                </div>
                            </div>
                        </div>
                    </div>

                </fieldset>
                <div class="row div-form-control">
                    <div class="col-md-12">
                        <div class="form-group">
                            <button type="submit" asp-page-handler="ChangePassword" class="btn btn-primary"><i class="icon-floppy-disk position-right"></i>تعغیر رمز عبور</button>

                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    @if (ModelState.ErrorCount > 0)
                    {
                        <label class="control-label text-bold text-danger">
                            لطفا دقت نماید
                        </label>
                        <ul>
                            @foreach (var item in ViewData.ModelState.Values)
                            {
                                foreach (var error in item.Errors)
                                {
                                    <li style="color:red">@error.ErrorMessage</li>
                                }
                            }
                        </ul>
                    }
                    else
                    {
                        <div style="width:100%; text-align:center">
                            <label class="control-label text-bold text-success">@Model.Message</label>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="Security/Shared/_ValidationScriptsPartial" />
}

NHCM.WebUI/Pages/Security/Roles.cshtml
@page
@model NHCM.WebUI.Pages.Security.RolesModel
@{
    ViewData["Title"] = "Roles";
    Layout = "~/Pages/Security/Shared/_SecuritySharedLayout.cshtml";
}




<div class="panel-heading">
    

    <h1 class="panel-title">ایجاد نقش</h1>
</div>

<div class="panel-body">
    <form asp-page-handler="CreateRole" method="post">

        <fieldset class="content-group">
            <legend>برای ایجاد حقوق استفاده از سیستم از این فورم استفاده نماید</legend>
            <div class="row">
                <div class="col-md-6 pull-right">

                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 pull-right">
                            <div class="form-group">
                                <label asp-for="@Model.RoleName" class="text-bold">
                                    نام نقش

                                </label>
                                <span asp-validation-for="@Model.RoleName" class="text-danger"></span>
                                <input asp-for="@Model.RoleName" class="form-control" />



                                <div class="form-control-feedback">
                                    <i>

                                    </i>
                                </div>
                            </div>
                        </div>
                    </div>



                </div>

                <div class="col-md-6 pull-right">
                    <div class="row">
                        <div class="col-md-12">


                            @if (ModelState.ErrorCount > 0)
                            {
                                <label class="control-label text-bold text-danger">
                                    لطفا دقت نماید
                                </label>
                                <ul>
                                    @foreach (var item in ViewData.ModelState.Values)
                                    {
                                        foreach (var error in item.Errors)
                                        {
                                            <li style="color:red">@error.ErrorMessage</li>
                                        }
                                    }
                                </ul>
                            }
                            else
                            {
                                <ul>
                                    <li style="color:green"> @Model.Message </li>
                                </ul>
                            }


                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <div class="row div-form-control">
            <div class="col-md-12">
                <div class="form-group">
                    <button type="submit"  class="btn btn-primary" action="save"><i class="icon-floppy-disk position-right"></i>ثبت نقش</button>
                </div>
            </div>
        </div>
    </form>
</div>




@section Scripts{ 
    <partial name="Security/Shared/_ValidationScriptsPartial" />
}

NHCM.WebUI/Pages/Security/UserInRole.cshtml
@page
@model NHCM.WebUI.Pages.Security.UserInRoleModel
@{
    ViewData["Title"] = "UserInRole";
    Layout = "~/Pages/Security/Shared/_SecuritySharedLayout.cshtml";
}

<div class="panel-heading">
    <h1 class="panel-title">تعین حقوق و نقش های کاربر</h1>
</div>

<div class="panel-body">
    <form asp-page-handler="AddUserInRole" method="post" class="form main-form page-component" type="form">
        <fieldset class="content-group">
            <div class="row">
                <div class="col-md-6 pull-right">

                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 pull-right">
                            <div class="form-group">
                                <label class="text-bold">
                                    کاربران
                                    <span class="text-danger"></span>
                                </label>
                                <select asp-items="@Model.ListOfUsers" asp-for="@Model.UserId" class="form-control select"></select>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12 pull-right">
                            <div class="form-group">
                                <label class="text-bold">
                                  حقوق و نقش ها
                                    <span class="text-danger"></span>
                                </label>
                                <select asp-items="@Model.ListOfRoles" asp-for="@Model.RoleId" class="form-control select"></select>
                            </div>
                        </div>
                    </div>




                </div>

                <div class="col-md-6 pull-right">
                    <div class="row">
                        <div class="col-md-12">


                            @if (ModelState.ErrorCount > 0)
                            {
                                <label class="control-label text-bold text-danger">
                                    لطفا دقت نماید
                                </label>
                                <ul>
                                    @foreach (var item in ViewData.ModelState.Values)
                                    {
                                        foreach (var error in item.Errors)
                                        {
                                            <li style="color:red">@error.ErrorMessage</li>
                                        }
                                    }
                                </ul>
                            }
                            else
                            {
                                <label style="color:green">
                                    @Model.Message
                                </label>
                            }


                        </div>
                    </div>
                </div>
            </div>
        </fieldset>





        <div class="row div-form-control">
            <div class="col-md-12">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" ><i class="icon-floppy-disk position-right"></i>تعیین نقش</button>

                </div>
            </div>
        </div>
    </form>
</div>







@section Scripts{

    <partial name="Security/Shared/_ValidationScriptsPartial" />
}